# -*- coding: utf-8 -*-
"""Articles.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lC_-s3vON_KKxHHRug_z_UHv1RPT5oKZ
"""

# !mkdir -p ~/.kaggle
# !cp kaggle.json ~/.kaggle/
# !cp kaggle.json ~/.kaggle/
# !chmod 600 ~/.kaggle/kaggle.json
# !kaggle datasets download -d gspmoreira/articles-sharing-reading-from-cit-deskdrop
# !unzip articles-sharing-reading-from-cit-deskdrop.zip

import pandas as pd
import numpy as np

df1=pd.read_csv("shared_articles.csv")
df2=pd.read_csv("users_interactions.csv")

df1.head()
df2.head()